# Datastax

#The -g flag starts a Node with Graph Model enabled
#The -s flag starts a Node with Search Engine enabled
#The -k flag starts a Node with Spark Analytics enabled
#docker run -e DS_LICENSE=accept --memory 4g --name my-dse -d datastax/dse-server -g -s -k

#docker run -e DS_LICENSE=accept --link my-dse -p 9091:9091 --memory 1g --name my-studio -d datastax/dse-studio

# studio

version: '3'
services:
  cassandra:
    image: datastax/dse-server
    networks:
    - localhost
    ports:
#      - "4040:4040"
#      - "7080:7080"
#      - "7199:7199"
#      - "8182:8182"
#      - "8983:8983"
      - "9042:9042"
    volumes:
      - /home/vinicius/development/docker/cassandra/datastax/config:/config
#      - /home/vinicius/development/docker/cassandra/datastax:/var/lib/cassandra/
#      - /home/vinicius/development/docker/cassandra/datastax/logs:/var/lib/cassandra/commit_logs
#      - /home/vinicius/development/docker/cassandra/datastax/cache:/var/lib/cassandra/saved_caches
    environment:
      - DS_LICENSE=accept
    container_name: "dse"
    command:
     -s
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1

#  cassandra-studio:
#    image: datastax/dse-studio:latest
#    networks:
#    - localhost
#    ports:
#    - 9091:9091
networks:
  localhost:
    driver: bridge