spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: testKeySpace
#      schema-action: create-if-not-exists
      fetch-size: 2000
      serial-consistency-level: local-one

#cassandra:
#  contactpoints: 127.0.0.1
#cassandra:
#  port: 9042
#cassandra:
#  keyspace: testKeySpace
